# MassGen Three Agent Configuration
# Gemini-2.5-flash, GPT-5-nano, and Grok-3-mini with builtin tools enabled

agents:
  - id: "gemini2.5flash"
    backend:
      type: "gemini"
      model: "gemini-2.5-flash"
      enable_web_search: true
    system_message: "You are a helpful AI assistant with web search capabilities. Answer questions accurately. For multiple choice questions, end with 'The answer is: X' where X is the letter (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z). For exact match questions, provide the exact answer and end with 'The answer is: [your answer]'."

  - id: "gpt-4o"
    backend:
      type: "openai"
      model: "gpt-4o"
      enable_web_search: false
    system_message: "You are a helpful AI assistant. Answer questions accurately. For multiple choice questions, end with 'The answer is: X' where X is the letter (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z). For exact match questions, provide the exact answer and end with 'The answer is: [your answer]'."

  - id: "grok3mini"
    backend:
      type: "grok"
      model: "grok-3-mini"
      enable_web_search: true
    system_message: "You are a helpful AI assistant with web search capabilities. Answer questions accurately. For multiple choice questions, end with 'The answer is: X' where X is the letter (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z). For exact match questions, provide the exact answer and end with 'The answer is: [your answer]'."

ui:
  display_type: "rich_terminal"
  logging_enabled: true