# MassGen v3 Single Agent Configuration
# Simple configuration for single agent operation

agent:
  id: "assistant"
  backend:
    type: "openai"
    model: "gpt-4o-mini"
    # api_key: "your-api-key-here"  # Optional, uses OPENAI_API_KEY env var
  system_message: "You are a helpful AI assistant providing accurate and concise responses."

ui:
  display_type: "terminal"  # Options: terminal, simple
  logging_enabled: true

# Optional: Backend-specific parameters
# backend_params:
#   temperature: 0.7
#   max_tokens: 2000
#   enable_web_search: false
#   enable_code_interpreter: false